### ISSUE TITLE
 Limited to only 20.4.0 node version.

### ISSUE THREAD

**Issue by jhaseel** [VadimDez/ngx-filter-pipe#158]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [x] Feature request
- [ ] Documentation issue or request
```
hi guys

I am having problems trying to deploy using version 3.0.0 as the library is limited to use Node js 20.4.0.

could you extend the support to node 20.4.0 or higher please?

`sterr: error ngx-filter-pipe@3.0.0: The engine "node" is incompatible with this module. Expected version "20.4.0". Got "20.13.1"
`

**Comment by bernardo-amaral** [comment]
Same problem here!

```
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'ngx-filter-pipe@3.0.0',
npm warn EBADENGINE   required: { node: '20.4.0', npm: '9.7.2' },
npm warn EBADENGINE   current: { node: 'v20.12.2', npm: '10.8.1' }
npm warn EBADENGINE }
```

**Comment by Simon-IEEECS** [comment]
Yeah that was a clear mistake. Author put an exact Node.js version instead of >=. Anyone home?

**Comment by bernardo-amaral** [comment]
> Yeah that was a clear mistake. Author put an exact Node.js version instead of >=. Anyone home?

it seems that the author abandoned the project...
