### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by sergey-morenets** [VadimDez/ngx-filter-pipe#41]
Hi

Unfortunately I couldn't install this dependency, even if I run install it under root(npm install ng2-filter-pipe --save). I always get this error. Please advise.

16584 verbose stack Error: EPERM: operation not permitted, rename 'D:\\angular\node_modules\json3' -> 'D:\\angular\node_modules\.json3.DELETE'
16585 verbose cwd D:\\angular
16586 verbose Windows_NT 6.1.7601
16587 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user_admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "ng2-filter-pipe" "--save"
16588 verbose node v7.9.0
16589 verbose npm  v5.3.0
16590 error path D:\\angular\node_modules\json3
16591 error code EPERM
16592 error errno -4048
16593 error syscall rename
16594 error Error: EPERM: operation not permitted, rename 'D:\\angular\node_modules\json3' -> 'D:\\angular\node_modules\.json3.DELETE'
16594 error  { Error: EPERM: operation not permitted, rename 'D:\\angular\node_modules\json3' -> 'D:\\angular\node_modules\.json3.DELETE'
16594 error   cause:
16594 error    { Error: EPERM: operation not permitted, rename 'D:\\angular\node_modules\json3' -> 'D:\\angular\node_modules\.json3.DELETE'
16594 error      errno: -4048,
16594 error      code: 'EPERM',
16594 error      syscall: 'rename',
16594 error      path: 'D:\\angular\\node_modules\\json3',
16594 error      dest: 'D:\\angular\\node_modules\\.json3.DELETE' },

**Comment by VadimDez** [comment]
have you tried `npm install ngx-filter-pipe --save` ?

**Comment by sergey-morenets** [comment]
Hi @VadimDez 

I tried to run your command(as Administrator) but the error still remained.

**Comment by VadimDez** [comment]
can you install any but this package?
i can't see anything related to this package.
Do you have an antivirus running, then - https://github.com/react-community/create-react-native-app/issues/191#issuecomment-304073970
