### ISSUE TITLE
AOT support

### ISSUE THREAD

**Issue by sergey-morenets** [VadimDez/ngx-filter-pipe#42]
Hi 

Do you have plans to support AOT compilation? I use ngx-filter dependency and received the following message during rollup:

'FilterPipeModule' is not exported by 'node_modules\ngx-filter-pipe\dist\src\ngx-filter.module.js'

https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

Thanks

**Comment by VadimDez** [comment]
Are you using webpack or systemjs ?
Try to use `dist/bundles/ngx-filter-pipe.umd.js` instead of `dist\src\ngx-filter.module.js`. see if that helps.

**Comment by it-discovery** [comment]
@VadimDez Hi. I am using Angular CLI 1.4.4. 
How can I change this bundle?

**Comment by VadimDez** [comment]
i've just tried version `1.0.0` myself, didn't see any errors.
Could you show me how do you `import` and `use` `ngx-filter-pipe` ?

**Comment by it-discovery** [comment]
Hi @VadimDez 

I just re-checked this behavior with latest versions of Angular(4.4.4) and your library(1.0.0) following this guide: https://angular.io/guide/aot-compiler

However I got error message at rollup stage executing command: node_modules/.bin/rollup -c rollup-config.js

Error message:

'FilterPipeModule' is not exported by 'node_modules\ngx-filter-pipe\dist\src\ngx-filter.module.js'
'FilterPipeModule' is not exported by 'node_modules\ngx-filter-pipe\dist\src\ngx-filter.module.js'
[!] Error: 'FilterPipeModule' is not exported by node_modules\ngx-filter-pipe\dist\index.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
src\app\app.module.js (22:9)
22: import { FilterPipeModule } from 'ngx-filter-pipe';

**Comment by VadimDez** [comment]
Should be fixed now in `2.0.0`
