### ISSUE TITLE
Filter on a object property which has space

### ISSUE THREAD

**Issue by suvonkar** [VadimDez/ngx-filter-pipe#43]
@VadimDez , How I can use the filterBy on a object property which has space.

Like, I want to filter on user name, where user name has space.

Example: I have a user 'John Writer'. If I filter with 'John' it is working fine. But if I filter with 'John W' then nothing is coming.

**Comment by VadimDez** [comment]
i've tested this - https://github.com/VadimDez/ngx-filter-pipe/blob/master/examples/ng-cli/src/app/shared/ngx-filter.pipe.spec.ts#L228-L245
Seems to be working correctly
