### ISSUE TITLE
How to call filterPipe transform from Component ?

### ISSUE THREAD

**Issue by rpusarla** [VadimDez/ngx-filter-pipe#50]
Hi, 
Can you please advise how do we call FilterPipe transform from Component file ? When I am calling as below, it's throwing an error that "Property 'FilterPipe' does not exist on type 'FilterPipeModule'". Can you please advise ?

FilterPipeModule.prototype.FilterPipe

**Comment by VadimDez** [comment]
Released `1.0.2`.
See how to use it https://github.com/VadimDez/ngx-filter-pipe#use-filterpipe-in-a-component
