### ISSUE TITLE
How to refresh the arrays?

### ISSUE THREAD

**Issue by SvenBudak** [VadimDez/ngx-filter-pipe#61]
In use is the latest verison of Angular (5.2.0) and the latest version of ngx-filter-pipe (2.1.0)
I use ngx-translate to load my language texts. When i load the site all works fine with the filter... But when i change the language ngx-filter-pipe still got the old language array in cache. How can i fix this?

**Comment by RobertThwaite** [comment]
May not be a nice way of doing it but you could refresh the component with a ngIf

**Comment by BamiGorengo** [comment]
Hmm yeah sounds ugly ^^ i am verry new in programming, so i don't know the correct way. But is it not better with observable? Is there any example for this maybe?

**Comment by RobertThwaite** [comment]
if you set up a codepen or alternative I can take a quick look

**Comment by BamiGorengo** [comment]
I upload the project: https://som-tools.upperyard.de

**.htpasswd**
Username: Demo
Password: NsExR3PrhZ4J

I can create a stackbliz but would be nicer when i just can give access to my git repository.

**Comment by RobertThwaite** [comment]
Hi Bami,

Ngx translate is not changing the variable, simply printing it translated. Filter-pipe is working correctly here.

For example when on the "development" tab I searched "Strength", then changed the language to "Spanish". Although the text has changed on the UI the variable "abilitie.name" is still "Strength".

You will need to use NGX translate to actually change the Variables.

**Comment by BamiGorengo** [comment]
i am not sure that i understand... but... so i dont need to work with observables here?
